version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "daily"
    target-branch: "main"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
