version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - ".github/actions/setup-dependencies"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(github-actions)"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(javascript)"
    target-branch: "main"
    groups:
      javascript:
        patterns:
          - "*"
