#!/bin/bash
set -e

printf "Running Mandatory Checks \n"

just --quiet gitleaks-detect just-format prettier-check

printf "Mandatory Checks Passed \n"
printf "Running Optional Checks \n"

# shellcheck disable=SC2045,SC2028,SC2086,SC2206,SC2128
for script in $(ls -1 githooks/pre-commit-scripts/*.sh 2>/dev/null); do
  bash $script
done

printf "Optional Checks Passed \n"
