name: "Code Quality"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  packages: read
  statuses: write
  security-events: write

jobs:
  check-code-quality:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies

      # Lint and Format everything
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v7.1.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          LINTER_RULES_PATH: .github/super-linter-configurations
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JSON: false

  check-markdown-links:
    name: Check Markdown links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Check Markdown links
        uses: UmbrellaDocs/action-linkspector@v1.2.4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          config_file: .github/other-configurations/.linkspector.yml
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: nofilter

  check-justfile-format:
    name: Check Justfile Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Just
        uses: extractions/setup-just@v2

      - name: Check Justfile Format
        run: just just-format-check

  check-javascript-code:
    name: Check JavaScript Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Check JavaScript Formatting
        run: just prettier-check

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: just eslint-with-sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3.27.3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

  run-codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3.27.3
        with:
          languages: javascript
          queries: security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3.27.3
